version: 2.1

orbs:
  win: circleci/windows@2.2.0

workflows:
  main:
    jobs:
        - test:
            name: "Test | v3.7 | Linux"
            v: "3.7"
            mode: "TEST"
        - test:
            name: "Test | v3.8 | Linux"
            v: "3.8"
            mode: "TEST"
        - test:
            name: "Test | v3.9 | Linux"
            v: "3.9"
            mode: "TEST"
        - test:
            name: "Test | v3.10 | Linux"
            v: "3.10"
            mode: "TEST"
        ### NOTEBOOKS
        - test:
            name: "Notebook | v3.7 | Linux"
            v: "3.7"
            mode: "NOTEBOOK"
        - test:
            name: "Notebook | v3.8 | Linux"
            v: "3.8"
            mode: "NOTEBOOK"
        - test:
            name: "Notebook | v3.9 | Linux"
            v: "3.9"
            mode: "NOTEBOOK"
        - test:
            name: "Notebook | v3.10 | Linux"
            v: "3.10"
            mode: "NOTEBOOK"
        ### LINTER
        - test:
            name: "Linter | Linux"
            v: "3.10"
            mode: "LINTER"
        - Pip
        - Windows   
        #- test:
        #    name: "Linux -  v3.11"  # missing Torchvision
        #    v: "3.11"

jobs:
  test:
    parameters:
      v:
        type: string
        default: "3.7"
      mode:
        type: string
        default: "ALL"
    resource_class: large
    docker:
      # https://circleci.com/docs/circleci-images#language-image-variants
      - image: "cimg/python:<< parameters.v >>"
    steps:

      - checkout

      - run:
          name: Install EVA package from GitHub repo with all dependencies
          command: |
            "python<< parameters.v >>" -m venv test_evadb
            source test_evadb/bin/activate
            pip install ".[dev]"

      - run:
          name: Test and upload coverage report to coveralls
          command: |
            source test_evadb/bin/activate
            bash script/test/test.sh -m "<< parameters.mode >>"
    
  Windows:
    executor: win/default
    parameters:
      v:
        type: string
        default: "3.10" 
    steps:
      - checkout

      - run: 
          name: Test windows
          command: |
            Set-StrictMode -Version Latest
            $ErrorActionPreference = 'Continue'
            pip install virtualenv
            virtualenv test_evadb
            test_evadb\Scripts\activate
            pip install ".[dev]"       
            bash script\test\test.sh

  Pip:
    resource_class: large
    docker:
      - image: "cimg/python:3.10"
    steps:

      - checkout

      - run:
          name: Install EVA package from pip and start server
          command: |
            pip install --upgrade pip
            pip install evadb
            bash script/test/package.sh
